{{- if .Values.domain }}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name:  {{ include "k8s-service.fullname" . }}
  namespace: {{ .Release.Name }}
  annotations:
    {{- if not (eq .Values.uriPrefix "/") }}
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    {{- end }}
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_set_header l5d-dst-override $service_name.$namespace.svc.cluster.local:$service_port;
      grpc_set_header l5d-dst-override $service_name.$namespace.svc.cluster.local:$service_port;
spec:
  rules:
    - host: {{ .Values.domain }}
      http:
        paths:
          - path: {{ .Values.uriPrefix }}{{ if not (eq .Values.uriPrefix "/") }}(/|$)(.*){{ end }}
            backend:
              serviceName: {{ include "k8s-service.fullname" . }}
              servicePort: 80
{{- end }}